/* AmzLoss backlink directory.
   Curated list is stored in LIST. Verified submissions from visitors are
   stored in localStorage and rendered so every verified site gets a backlink.
*/
window.AMZLOSS_DIRECTORY = {
  categories: [
    "Affiliate Tools",
    "Blogging",
    "SEO",
    "Reviews",
    "Deals & Coupons",
    "Finance",
    "Lifestyle",
    "Tech & Software",
    "SaaS",
    "Web Development",
    "Coding & Programming",
    "AI & Machine Learning",
    "Gadgets & Electronics",
    "Gaming",
    "Fashion & Apparel",
    "Beauty & Cosmetics",
    "Health & Fitness",
    "Wellness & Mental Health",
    "Fitness Equipment",
    "Nutrition & Supplements",
    "Home & Garden",
    "Home Improvement",
    "Interior Design",
    "Kitchen & Cooking",
    "Food & Recipes",
    "Pets & Pet Care",
    "Travel & Tourism",
    "Vacation Rentals",
    "Automotive & Cars",
    "Motorcycles",
    "Sports & Outdoors",
    "Fishing & Hunting",
    "Outdoor Gear",
    "Photography",
    "Videography & Editing",
    "Music & Audio",
    "Books & Reading",
    "Education & E-learning",
    "Online Courses",
    "Career & Jobs",
    "Business & Entrepreneurship",
    "Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Copywriting",
    "Web Design",
    "Cryptocurrency & Web3",
    "Investing & Stocks",
    "Real Estate",
    "Insurance",
    "Banking & Credit Cards",
    "Dating & Relationships",
    "Weddings",
    "Parenting & Family",
    "Kids & Toys",
    "Baby Products",
    "DIY & Crafts",
    "Hobbies & Collectibles",
    "Art & Design",
    "News & Media",
    "Entertainment",
    "Movies & Streaming",
    "Anime & Comics",
    "Spirituality & Religion",
    "Sustainability & Eco",
    "Green Living",
    "B2B Services",
    "Freelancing",
    "E-commerce & Dropshipping",
    "Cannabis & CBD",
    "Vaping & Smoking Alternatives",
    "Language Learning",
    "University & Study Abroad",
    "Government & Legal",
    "Nonprofit & Charity",
    "Local Business",
    "Insurance & Retirement",
    "Personal Development",
    "Productivity Tools",
    "Remote Work",
    "Side Hustles"
  ],
  LIST: [
    {
      name: "AmzLoss",
      url: "https://amzloss.com",
      category: "Affiliate Tools",
      description: "Audit your Amazon Associates earnings report and compare affiliate network commission rates."
    }
  ]
};

window.AMZLOSS_FORM_ENDPOINT = "https://script.google.com/macros/s/AKfycbzFrgHm0fkVP3QLqFTKYlFM8Ba460BugRz6fBpdZaOgDwniteyuAr9ZPXp12SEO_R23/exec";
window.AMZLOSS_ACCESS_KEY = "";