/* AmzLoss backlink directory.
   Curated list is stored in LIST. Verified submissions from visitors are
   stored in localStorage and rendered so every verified site gets a backlink.
*/
window.AMZLOSS_DIRECTORY = {
  categories: [
    "Affiliate Tools",
    "Blogging",
    "SEO",
    "Reviews",
    "Deals & Coupons",
    "Finance",
    "Lifestyle",
    "Tech & Software",
    "SaaS",
    "Web Development",
    "Coding & Programming",
    "AI & Machine Learning",
    "Gadgets & Electronics",
    "Gaming",
    "Fashion & Apparel",
    "Beauty & Cosmetics",
    "Health & Fitness",
    "Wellness & Mental Health",
    "Fitness Equipment",
    "Nutrition & Supplements",
    "Home & Garden",
    "Home Improvement",
    "Interior Design",
    "Kitchen & Cooking",
    "Food & Recipes",
    "Pets & Pet Care",
    "Travel & Tourism",
    "Vacation Rentals",
    "Automotive & Cars",
    "Motorcycles",
    "Sports & Outdoors",
    "Fishing & Hunting",
    "Outdoor Gear",
    "Photography",
    "Videography & Editing",
    "Music & Audio",
    "Books & Reading",
    "Education & E-learning",
    "Online Courses",
    "Career & Jobs",
    "Business & Entrepreneurship",
    "Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Copywriting",
    "Web Design",
    "Cryptocurrency & Web3",
    "Investing & Stocks",
    "Real Estate",
    "Insurance",
    "Banking & Credit Cards",
    "Dating & Relationships",
    "Weddings",
    "Parenting & Family",
    "Kids & Toys",
    "Baby Products",
    "DIY & Crafts",
    "Hobbies & Collectibles",
    "Art & Design",
    "News & Media",
    "Entertainment",
    "Movies & Streaming",
    "Anime & Comics",
    "Spirituality & Religion",
    "Sustainability & Eco",
    "Green Living",
    "B2B Services",
    "Freelancing",
    "E-commerce & Dropshipping",
    "Cannabis & CBD",
    "Vaping & Smoking Alternatives",
    "Language Learning",
    "University & Study Abroad",
    "Government & Legal",
    "Nonprofit & Charity",
    "Local Business",
    "Insurance & Retirement",
    "Personal Development",
    "Productivity Tools",
    "Remote Work",
    "Side Hustles"
  ],
  LIST: [
    {
      name: "AmzLoss",
      url: "https://amzloss.com",
      category: "Affiliate Tools",
      description: "Free Amazon Associates tools: commission calculator, 2026 rate table, earnings audit, break-even calculator, affiliate network comparison, link builder, backlink checker, IndexNow URL submitter and a curated backlink directory."
    }
  ]
};

window.AMZLOSS_FORM_ENDPOINT = "https://script.google.com/macros/s/AKfycbwNImdVUndx662cRCMKLJIZU3OxUtoQx_vP_BrtcUlyaVxw8mbPZxF8kzPlqKakmbsU/exec";
window.AMZLOSS_ACCESS_KEY = "";
/* Sites removed by the weekly backlink audit (they stopped linking back).
   Their domains are filtered out of the directory listing. */
window.AMZLOSS_REMOVED = [];