import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const src = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// Each map is an ordered list of [english, translated] pairs applied via split/join
// (so regex-special characters are treated literally). Body + meta copy only;
// structural / path fixes are handled in build().
const MAPS = {
  es: [
    ['Free Amazon Affiliate Tools | Earnings Audit | AmzLoss', 'Herramientas gratuitas para afiliados de Amazon | Auditoría de ganancias | AmzLoss'],
    ['Free Amazon affiliate tools: audit your earnings, calculate commissions, check 2026 rates, build links and grow backlinks — all in your browser, no sign-up.', 'Herramientas gratuitas para afiliados de Amazon: audita tus ganancias, calcula comisiones, consulta las tarifas 2026, crea enlaces y haz crecer tus backlinks; todo en tu navegador, sin registro.'],
    ['amazon affiliate tools, amazon associates earnings audit, amazon commission calculator, amazon associates commission rate table, amazon affiliate rate cuts 2026, amazon affiliate underpayment, free affiliate tools, url submitter, indexnow, backlink directory, link builder, webmaster tools', 'herramientas para afiliados de amazon, auditoría de ganancias de amazon associates, calculadora de comisiones de amazon, tabla de tarifas de amazon associates, recortes de tarifas amazon 2026, pagos incorrectos de afiliados amazon, herramientas de afiliación gratis, enviador de urls, indexnow, directorio de backlinks, creador de enlaces, herramientas para webmasters'],
    ['Free affiliate and webmaster tools: Amazon Associates earnings audit, commission calculators, rate tables, link tools, a URL submitter and a backlink directory. Everything runs in your browser.', 'Herramientas gratuitas para afiliados y webmasters: auditoría de ganancias de Amazon Associates, calculadoras de comisiones, tablas de tarifas, herramientas de enlaces, un enviador de URLs y un directorio de backlinks. Todo funciona en tu navegador.'],
    ['A growing set of free affiliate and webmaster tools that run entirely in your browser: earnings audit, commission calculators, link tools, a URL submitter and a backlink directory.', 'Un conjunto en crecimiento de herramientas gratuitas para afiliados y webmasters que funcionan enteramente en tu navegador: auditoría de ganancias, calculadoras de comisiones, herramientas de enlaces, un enviador de URLs y un directorio de backlinks.'],
    ['100% free', '100% gratis'],
    ['Affiliate & webmaster tools that run in your browser — no sign-up, no install.', 'Herramientas de afiliación y para webmasters que funcionan en tu navegador; sin registro, sin instalación.'],
    ['Free tools that help you earn more from every link, click &amp; report', 'Herramientas gratuitas que te ayudan a ganar más con cada enlace, clic e informe'],
    ['Not a single-purpose tool. A complete earning toolkit.', 'No es una herramienta de un solo propósito. Todo un conjunto de herramientas para ganar.'],
    ['AmzLoss gives Amazon associates and independent webmasters a free, private toolkit to audit earnings, sanity-check commissions, submit URLs and build backlinks — without handing your data to anyone.', 'AmzLoss ofrece a los afiliados de Amazon y a webmasters independientes un conjunto de herramientas gratuito y privado para auditar ganancias, verificar comisiones, enviar URLs y construir backlinks, sin entregar tus datos a nadie.'],
    ['Explore all tools', 'Explorar todas las herramientas'],
    ['Audit my Amazon report', 'Auditar mi reporte de Amazon'],
    ['No account. No sign-up. Your data never leaves your device.', 'Sin cuenta. Sin registro. Tus datos nunca salen de tu dispositivo.'],
    ['8+ free tools, one toolkit', '8+ herramientas gratis, un solo conjunto'],
    ['30+ platforms to submit URLs', '30+ plataformas para enviar URLs'],
    ['100% processed in-browser only', '100% procesado solo en el navegador'],
    ['The problem', 'El problema'],
    ['Amazon quietly made affiliate earnings harder to trust', 'Amazon hizo que las ganancias de afiliados sean más difíciles de confiar'],
    ['Three things quietly work against Amazon associates:', 'Tres cosas trabajan en tu contra como afiliado de Amazon:'],
    ['Rates cut up to 50%', 'Tarifas recortadas hasta 50%'],
    ['Categories like furniture and tools dropped from 8% to 3% — a 62% pay cut with no warning.', 'Categorías como muebles y herramientas bajaron de 8% a 3%, una reducción del 62% sin aviso.'],
    ['Reporting got weaker', 'Los informes se debilitaron'],
    ['The dashboard hides the math. You see a number, not how it was calculated.', 'El panel oculta los cálculos. Ves un número, no cómo se calculó.'],
    ['Nobody checks the math', 'Nadie revisa los cálculos'],
    ['If a commission is miscalculated or a click stolen, you will not catch it by glancing at the summary.', 'Si una comisión se calcula mal o te roban un clic, no lo notarás mirando el resumen.'],
    ['That is where AmzLoss helps — free tools that show the math, check the rates and help you get found.', 'Ahí es donde AmzLoss ayuda: herramientas gratuitas que muestran los cálculos, verifican las tarifas y te ayudan a que te encuentren.'],
    ['How it works', 'Cómo funciona'],
    ['Three steps, no account required', 'Tres pasos, sin cuenta requerida'],
    ['Pick a tool', 'Elige una herramienta'],
    ['Open any tool on this site. Everything runs locally in your browser.', 'Abre cualquier herramienta en este sitio. Todo se ejecuta localmente en tu navegador.'],
    ['Use it privately', 'Úsala con privacidad'],
    ['Paste your numbers, rates or URLs. Nothing is uploaded or stored.', 'Pega tus números, tarifas o URLs. Nada se sube ni se guarda.'],
    ['Act on the result', 'Actúa según el resultado'],
    ['Audit a report, submit a URL, or list your site in the backlink directory.', 'Audita un reporte, envía una URL o lista tu sitio en el directorio de backlinks.'],
    ['Tools', 'Herramientas'],
    ['Free tools for Amazon associates &amp; webmasters', 'Herramientas gratuitas para afiliados de Amazon y webmasters'],
    ['Commission Calculator', 'Calculadora de comisiones'],
    ['Estimate earnings from clicks, price and category rate — instantly.', 'Estima ganancias a partir de clics, precio y tarifa de categoría, al instante.'],
    ['Rate Table', 'Tabla de tarifas'],
    ['Current Amazon Associates commission rates by category, with recent cuts.', 'Tarifas de comisión actuales de Amazon Associates por categoría, con recortes recientes.'],
    ['Earnings Audit', 'Auditoría de ganancias'],
    ['Upload a report and check the math yourself — your data stays on your device.', 'Sube un reporte y verifica los cálculos tú mismo; tus datos quedan en tu dispositivo.'],
    ['Break-even Calculator', 'Calculadora de punto de equilibrio'],
    ['How many sales you need before a campaign pays for itself.', 'Cuántas ventas necesitas para que una campaña se pague sola.'],
    ['Network Calculator', 'Calculadora de redes'],
    ['Compare earnings across affiliate programs, not just Amazon.', 'Compara ganancias entre programas de afiliación, no solo Amazon.'],
    ['Link Builder', 'Creador de enlaces'],
    ['Turn any product URL into a clean, tagged affiliate link.', 'Convierte cualquier URL de producto en un enlace de afiliado limpio y etiquetado.'],
    ['URL Submitter', 'Enviador de URLs'],
    ['Ping 30+ platforms (Google, Bing, IndexNow) so new pages get indexed faster.', 'Notifica a más de 30 plataformas (Google, Bing, IndexNow) para indexar páginas más rápido.'],
    ['Backlink Directory', 'Directorio de backlinks'],
    ['List your site and discover others to grow referral traffic.', 'Lista tu sitio y descubre otros para crecer tu tráfico de referencia.'],
    ['A simple strategy', 'Una estrategia sencilla'],
    ['One quiet habit that compounds', 'Un hábito silencioso que se acumula'],
    ['Most associates optimize a page once and move on. The ones who grow treat indexing and backlinks as a weekly habit.', 'La mayoría optimiza una página una vez y sigue adelante. Quienes crecen tratan la indexación y los backlinks como un hábito semanal.'],
    ['Every Monday, pick one URL and submit it everywhere, then list one backlink. Small, consistent actions beat occasional sprints.', 'Cada lunes, elige una URL y envíala a todos lados, luego lista un backlink. Acciones pequeñas y constantes vencen a los sprints ocasionales.'],
    ['Free vs paid', 'Gratis vs de pago'],
    ['Everything free, no catch', 'Todo gratis, sin letra pequeña'],
    ['Free', 'Gratis'],
    ['Every tool on this site', 'Cada herramienta de este sitio'],
    ['No account needed', 'Sin cuenta necesaria'],
    ['Private by design', 'Privado por diseño'],
    ['Paid (never required)', 'De pago (nunca requerido)'],
    ['Sponsor the project', 'Patrocina el proyecto'],
    ['Remove ads', 'Quitar anuncios'],
    ['Priority feature requests', 'Solicitudes de funciones prioritarias'],
    ['Who it is for', 'Para quién es'],
    ['Built for people who publish and promote', 'Hecho para quienes publican y promocionan'],
    ['Amazon Associates', 'Afiliados de Amazon'],
    ['Check if rate cuts or miscalculations are costing you.', 'Verifica si los recortes o cálculos erróneos te están costando dinero.'],
    ['Webmasters', 'Webmasters'],
    ['Get pages indexed faster and grow referral traffic.', 'Indexa páginas más rápido y crece tu tráfico de referencia.'],
    ['Content creators', 'Creadores de contenido'],
    ['Turn product URLs into clean affiliate links in seconds.', 'Convierte URLs de productos en enlaces de afiliado limpios en segundos.'],
    ['Agencies', 'Agencias'],
    ['Give clients a private, branded earnings check.', 'Ofrece a clientes una verificación de ganancias privada y con tu marca.'],
    ['What people say', 'Lo que dicen'],
    ['Real feedback from affiliate publishers', 'Comentarios reales de publicadores afiliados'],
    ['Trusted by publishers', 'Con la confianza de publicadores'],
    ['Stay in the loop', 'Mantente al tanto'],
    ['New tools, rate-change alerts and indexing tips — no spam.', 'Nuevas herramientas, alertas de cambios de tarifas y consejos de indexación; sin spam.'],
    ['Get update', 'Recibir novedades'],
    ['We respect your inbox. Unsubscribe anytime.', 'Respetamos tu bandeja. Cancela cuando quieras.'],
    ['Frequently asked questions', 'Preguntas frecuentes'],
    ['Common questions about AmzLoss', 'Preguntas comunes sobre AmzLoss'],
    ['Are my details safe with AmzLoss?', '¿Están seguros mis datos con AmzLoss?'],
    ['Yes. Everything is processed in your browser. We never upload, store or see your earnings, links or URLs.', 'Sí. Todo se procesa en tu navegador. Nunca subimos, almacenamos ni vemos tus ganancias, enlaces ni URLs.'],
    ['Are these tools only for Amazon affiliates?', '¿Estas herramientas son solo para afiliados de Amazon?'],
    ['No. The audit, rate table, calculator and break-even tool focus on Amazon because that is where underpayment is hardest to verify, but the network calculator, link tools, URL submitter and backlink directory work for any webmaster.', 'No. La auditoría, la tabla de tarifas, la calculadora y la herramienta de punto de equilibrio se centran en Amazon porque allí es más difícil verificar pagos incorrectos, pero la calculadora de redes, las herramientas de enlaces, el enviador de URLs y el directorio de backlinks funcionan para cualquier webmaster.'],
    ['Do I need to create an account?', '¿Necesito crear una cuenta?'],
    ['No. Every tool works without sign-up. Your data never leaves your device.', 'No. Cada herramienta funciona sin registro. Tus datos nunca salen de tu dispositivo.'],
    ['Is AmzLoss really free?', '¿AmzLoss es realmente gratis?'],
    ['Yes. All tools are free. Paid options (sponsorship, ad removal) are never required.', 'Sí. Todas las herramientas son gratis. Las opciones de pago (patrocinio, quitar anuncios) nunca son requeridas.'],
    ['How do I report a bug or request a tool?', '¿Cómo reporto un error o pido una herramienta?'],
    ['Email admin@amzloss.com with the details. Feature requests from sponsors get priority.', 'Escribe a admin@amzloss.com con los detalles. Las solicitudes de funciones de patrocinadores tienen prioridad.'],
    ['Ready to take control of your affiliate earnings?', '¿Listo para tomar el control de tus ganancias de afiliado?'],
    ['Start with a free earnings audit — no account, no risk.', 'Empieza con una auditoría de ganancias gratuita; sin cuenta, sin riesgo.'],
    ['More tools', 'Más herramientas'],
    ['Guides', 'Guías'],
    ['Company', 'Compañía'],
    ['Discover more', 'Descubrir más'],
    ['AmzLoss', 'AmzLoss'],
    ['All rights reserved.', 'Todos los derechos reservados.'],
    ['Privacy-first tools that help you earn, verify and grow.', 'Herramientas centradas en la privacidad que te ayudan a ganar, verificar y crecer.'],
    ['Affiliate tools', 'Herramientas de afiliación'],
    ['Webmaster tools', 'Herramientas para webmasters'],
    ['About', 'Acerca de'],
    ['Pricing', 'Precios'],
    ['FAQ', 'Preguntas frecuentes'],
    ['Contact', 'Contacto'],
    ['Blog', 'Blog'],
    ['Terms', 'Términos'],
    ['Privacy', 'Privacidad'],
    ['Sitemap', 'Mapa del sitio'],
    ['Follow us', 'Síguenos'],
  ],
  de: [
    ['Free Amazon Affiliate Tools | Earnings Audit | AmzLoss', 'Kostenlose Amazon-Partner-Tools | Verdienst-Audit | AmzLoss'],
    ['Free Amazon affiliate tools: audit your earnings, calculate commissions, check 2026 rates, build links and grow backlinks — all in your browser, no sign-up.', 'Kostenlose Amazon-Partner-Tools: prüfe deine Verdienste, berechne Provisionen, sieh 2026-Tarife, baue Links und wachse mit Backlinks – alles im Browser, ohne Anmeldung.'],
    ['amazon affiliate tools, amazon associates earnings audit, amazon commission calculator, amazon associates commission rate table, amazon affiliate rate cuts 2026, amazon affiliate underpayment, free affiliate tools, url submitter, indexnow, backlink directory, link builder, webmaster tools', 'amazon partner tools, amazon partner verdienst audit, amazon provisionsrechner, amazon partner provisions-tariftabelle, amazon partner tarifkürzungen 2026, amazon partner fehlzahlung, kostenlose partner tools, url sender, indexnow, backlink verzeichnis, link builder, webmaster tools'],
    ['Free affiliate and webmaster tools: Amazon Associates earnings audit, commission calculators, rate tables, link tools, a URL submitter and a backlink directory. Everything runs in your browser.', 'Kostenlose Partner- und Webmaster-Tools: Amazon-Partner Verdienst-Audit, Provisionsrechner, Tariftabellen, Link-Tools, ein URL-Sender und ein Backlink-Verzeichnis. Alles läuft in deinem Browser.'],
    ['A growing set of free affiliate and webmaster tools that run entirely in your browser: earnings audit, commission calculators, link tools, a URL submitter and a backlink directory.', 'Eine wachsende Sammlung kostenloser Partner- und Webmaster-Tools, die vollständig in deinem Browser laufen: Verdienst-Audit, Provisionsrechner, Link-Tools, ein URL-Sender und ein Backlink-Verzeichnis.'],
    ['100% free', '100% kostenlos'],
    ['Affiliate & webmaster tools that run in your browser — no sign-up, no install.', 'Partner- und Webmaster-Tools, die in deinem Browser laufen – ohne Anmeldung, ohne Installation.'],
    ['Free tools that help you earn more from every link, click &amp; report', 'Kostenlose Tools, mit denen du mehr aus jedem Link, Klick und Bericht verdienst'],
    ['Not a single-purpose tool. A complete earning toolkit.', 'Nicht ein Tool für einen Zweck. Ein komplettes Verdienst-Toolkit.'],
    ['AmzLoss gives Amazon associates and independent webmasters a free, private toolkit to audit earnings, sanity-check commissions, submit URLs and build backlinks — without handing your data to anyone.', 'AmzLoss bietet Amazon-Partnern und unabhängigen Webmastern ein kostenloses, privates Toolkit, um Verdienste zu prüfen, Provisionen zu kontrollieren, URLs zu senden und Backlinks aufzubauen – ohne deine Daten weiterzugeben.'],
    ['Explore all tools', 'Alle Tools entdecken'],
    ['Audit my Amazon report', 'Meinen Amazon-Bericht prüfen'],
    ['No account. No sign-up. Your data never leaves your device.', 'Kein Konto. Keine Anmeldung. Deine Daten verlassen dein Gerät nie.'],
    ['8+ free tools, one toolkit', '8+ kostenlose Tools, ein Toolkit'],
    ['30+ platforms to submit URLs', '30+ Plattformen zum Senden von URLs'],
    ['100% processed in-browser only', '100% nur im Browser verarbeitet'],
    ['The problem', 'Das Problem'],
    ['Amazon quietly made affiliate earnings harder to trust', 'Amazon machte Partner-Verdienste schwerer zu vertrauen'],
    ['Three things quietly work against Amazon associates:', 'Drei Dinge wirken leise gegen Amazon-Partner:'],
    ['Rates cut up to 50%', 'Tarife um bis zu 50% gekürzt'],
    ['Categories like furniture and tools dropped from 8% to 3% — a 62% pay cut with no warning.', 'Kategorien wie Möbel und Werkzeug fielen von 8% auf 3% – eine Kürzung um 62% ohne Warnung.'],
    ['Reporting got weaker', 'Berichte wurden schwächer'],
    ['The dashboard hides the math. You see a number, not how it was calculated.', 'Das Dashboard versteckt die Rechnung. Du siehst eine Zahl, nicht wie sie berechnet wurde.'],
    ['Nobody checks the math', 'Niemand prüft die Rechnung'],
    ['If a commission is miscalculated or a click stolen, you will not catch it by glancing at the summary.', 'Wenn eine Provision falsch berechnet oder ein Klick gestohlen wird, bemerkst du es nicht beim Blick auf die Zusammenfassung.'],
    ['That is where AmzLoss helps — free tools that show the math, check the rates and help you get found.', 'Hier hilft AmzLoss – kostenlose Tools, die die Rechnung zeigen, Tarife prüfen und dir helfen, gefunden zu werden.'],
    ['How it works', 'So funktioniert es'],
    ['Three steps, no account required', 'Drei Schritte, kein Konto nötig'],
    ['Pick a tool', 'Wähle ein Tool'],
    ['Open any tool on this site. Everything runs locally in your browser.', 'Öffne ein Tool auf dieser Seite. Alles läuft lokal in deinem Browser.'],
    ['Use it privately', 'Nutze es privat'],
    ['Paste your numbers, rates or URLs. Nothing is uploaded or stored.', 'Füge deine Zahlen, Tarife oder URLs ein. Es wird nichts hochgeladen oder gespeichert.'],
    ['Act on the result', 'Handle nach dem Ergebnis'],
    ['Audit a report, submit a URL, or list your site in the backlink directory.', 'Prüfe einen Bericht, sende eine URL oder liste deine Seite im Backlink-Verzeichnis.'],
    ['Tools', 'Tools'],
    ['Free tools for Amazon associates &amp; webmasters', 'Kostenlose Tools für Amazon-Partner und Webmaster'],
    ['Commission Calculator', 'Provisionsrechner'],
    ['Estimate earnings from clicks, price and category rate — instantly.', 'Schätze Verdienste aus Klicks, Preis und Kategorie-Tarif – sofort.'],
    ['Rate Table', 'Tariftabelle'],
    ['Current Amazon Associates commission rates by category, with recent cuts.', 'Aktuelle Amazon-Partner-Provisionstarife nach Kategorie, mit aktuellen Kürzungen.'],
    ['Earnings Audit', 'Verdienst-Audit'],
    ['Upload a report and check the math yourself — your data stays on your device.', 'Lade einen Bericht hoch und prüfe die Rechnung selbst – deine Daten bleiben auf deinem Gerät.'],
    ['Break-even Calculator', 'Break-even-Rechner'],
    ['How many sales you need before a campaign pays for itself.', 'Wie viele Verkäufe du brauchst, bis sich eine Kampagne rechnet.'],
    ['Network Calculator', 'Netzwerk-Rechner'],
    ['Compare earnings across affiliate programs, not just Amazon.', 'Vergleiche Verdienste über Partnerprogramme, nicht nur Amazon.'],
    ['Link Builder', 'Link-Builder'],
    ['Turn any product URL into a clean, tagged affiliate link.', 'Verwandle jede Produkt-URL in einen sauberen, markierten Partner-Link.'],
    ['URL Submitter', 'URL-Sender'],
    ['Ping 30+ platforms (Google, Bing, IndexNow) so new pages get indexed faster.', 'Ping an 30+ Plattformen (Google, Bing, IndexNow), damit neue Seiten schneller indexiert werden.'],
    ['Backlink Directory', 'Backlink-Verzeichnis'],
    ['List your site and discover others to grow referral traffic.', 'Liste deine Seite und entdecke andere, um Empfehlungs-Traffic zu wachsen.'],
    ['A simple strategy', 'Eine einfache Strategie'],
    ['One quiet habit that compounds', 'Eine ruhige Gewohnheit, die sich addiert'],
    ['Most associates optimize a page once and move on. The ones who grow treat indexing and backlinks as a weekly habit.', 'Die meisten Partner optimieren eine Seite einmal und gehen weiter. Die, die wachsen, behandeln Indexierung und mehr als wöchentliche Gewohnheit.'],
    ['Every Monday, pick one URL and submit it everywhere, then list one backlink. Small, consistent actions beat occasional sprints.', 'Jeden Montag wähle eine URL und sende sie überall hin, dann liste einen Backlink. Kleine, beständige Aktionen schlagen gelegentliche Sprints.'],
    ['Free vs paid', 'Kostenlos vs. kostenpflichtig'],
    ['Everything free, no catch', 'Alles kostenlos, ohne Haken'],
    ['Every tool on this site', 'Jedes Tool auf dieser Seite'],
    ['No account needed', 'Kein Konto nötig'],
    ['Private by design', 'Privat von Natur aus'],
    ['Paid (never required)', 'Kostenpflichtig (nie nötig)'],
    ['Sponsor the project', 'Unterstütze das Projekt'],
    ['Remove ads', 'Werbung entfernen'],
    ['Priority feature requests', 'Priorisierte Feature-Wünsche'],
    ['Who it is for', 'Für wen es ist'],
    ['Built for people who publish and promote', 'Gemacht für Menschen, die veröffentlichen und bewerben'],
    ['Amazon Associates', 'Amazon-Partner'],
    ['Check if rate cuts or miscalculations are costing you.', 'Prüfe, ob Tarifkürzungen oder Fehlberechnungen dich Geld kosten.'],
    ['Webmasters', 'Webmaster'],
    ['Get pages indexed faster and grow referral traffic.', 'Lass Seiten schneller indexieren und wachse im Empfehlungs-Traffic.'],
    ['Content creators', 'Content-Ersteller'],
    ['Turn product URLs into clean affiliate links in seconds.', 'Verwandle Produkt-URLs in Sekunden in saubere Partner-Links.'],
    ['Agencies', 'Agenturen'],
    ['Give clients a private, branded earnings check.', 'Biete Kunden eine private, markengleiche Verdienst-Prüfung.'],
    ['What people say', 'Was Nutzer sagen'],
    ['Real feedback from affiliate publishers', 'Echtes Feedback von Partner-Publishern'],
    ['Trusted by publishers', 'Vertraut von Publishern'],
    ['Stay in the loop', 'Bleib auf dem Laufenden'],
    ['New tools, rate-change alerts and indexing tips — no spam.', 'Neue Tools, Tarifänderungs-Alarme und Indexierungs-Tipps – kein Spam.'],
    ['Get update', 'Updates erhalten'],
    ['We respect your inbox. Unsubscribe anytime.', 'Wir respektieren dein Postfach. Jederzeit abbestellbar.'],
    ['Frequently asked questions', 'Häufig gestellte Fragen'],
    ['Common questions about AmzLoss', 'Häufige Fragen zu AmzLoss'],
    ['Are my details safe with AmzLoss?', 'Sind meine Daten bei AmzLoss sicher?'],
    ['Yes. Everything is processed in your browser. We never upload, store or see your earnings, links or URLs.', 'Ja. Alles wird im Browser verarbeitet. Wir laden, speichern oder sehen deine Verdienste, Links oder URLs nie.'],
    ['Are these tools only for Amazon affiliates?', 'Sind diese Tools nur für Amazon-Partner?'],
    ['No. The audit, rate table, calculator and break-even tool focus on Amazon because that is where underpayment is hardest to verify, but the network calculator, link tools, URL submitter and backlink directory work for any webmaster.', 'Nein. Audit, Tariftabelle, Rechner und Break-even-Tool konzentrieren sich auf Amazon, weil dort Fehlzahlungen am schwersten zu prüfen sind, aber Netzwerk-Rechner, Link-Tools, URL-Sender und Backlink-Verzeichnis funktionieren für jeden Webmaster.'],
    ['Do I need to create an account?', 'Muss ich ein Konto erstellen?'],
    ['No. Every tool works without sign-up. Your data never leaves your device.', 'Nein. Jedes Tool funktioniert ohne Anmeldung. Deine Daten verlassen dein Gerät nie.'],
    ['Is AmzLoss really free?', 'Ist AmzLoss wirklich kostenlos?'],
    ['Yes. All tools are free. Paid options (sponsorship, ad removal) are never required.', 'Ja. Alle Tools sind kostenlos. Kostenpflichtige Optionen (Sponsoring, Werbung entfernen) sind nie nötig.'],
    ['How do I report a bug or request a tool?', 'Wie melde ich einen Fehler oder wünsche ein Tool?'],
    ['Email admin@amzloss.com with the details. Feature requests from sponsors get priority.', 'Schreibe an admin@amzloss.com mit den Details. Feature-Wünsche von Sponsoren haben Vorrang.'],
    ['Ready to take control of your affiliate earnings?', 'Bereit, die Kontrolle über deine Partner-Verdienste zu übernehmen?'],
    ['Start with a free earnings audit — no account, no risk.', 'Starte mit einem kostenlosen Verdienst-Audit – kein Konto, kein Risiko.'],
    ['More tools', 'Mehr Tools'],
    ['Guides', 'Anleitungen'],
    ['Company', 'Unternehmen'],
    ['Discover more', 'Mehr entdecken'],
    ['AmzLoss', 'AmzLoss'],
    ['All rights reserved.', 'Alle Rechte vorbehalten.'],
    ['Privacy-first tools that help you earn, verify and grow.', 'Datenschutz-zuerst-Tools, die dir helfen zu verdienen, zu prüfen und zu wachsen.'],
    ['Affiliate tools', 'Partner-Tools'],
    ['Webmaster tools', 'Webmaster-Tools'],
    ['About', 'Über uns'],
    ['Pricing', 'Preise'],
    ['FAQ', 'FAQ'],
    ['Contact', 'Kontakt'],
    ['Blog', 'Blog'],
    ['Terms', 'AGB'],
    ['Privacy', 'Datenschutz'],
    ['Sitemap', 'Sitemap'],
    ['Follow us', 'Folge uns'],
  ],
  pt: [
    ['Free Amazon Affiliate Tools | Earnings Audit | AmzLoss', 'Ferramentas gratuitas para afiliados da Amazon | Auditoria de ganhos | AmzLoss'],
    ['Free Amazon affiliate tools: audit your earnings, calculate commissions, check 2026 rates, build links and grow backlinks — all in your browser, no sign-up.', 'Ferramentas gratuitas para afiliados da Amazon: audite seus ganhos, calcule comissões, consulte as taxas de 2026, crie links e cresça com backlinks — tudo no navegador, sem cadastro.'],
    ['amazon affiliate tools, amazon associates earnings audit, amazon commission calculator, amazon associates commission rate table, amazon affiliate rate cuts 2026, amazon affiliate underpayment, free affiliate tools, url submitter, indexnow, backlink directory, link builder, webmaster tools', 'ferramentas para afiliados amazon, auditoria de ganhos amazon associates, calculadora de comissões amazon, tabela de taxas amazon associates, cortes de taxas amazon 2026, pagamento incorreto amazon, ferramentas de afiliação grátis, enviador de urls, indexnow, diretório de backlinks, criador de links, ferramentas para webmasters'],
    ['Free affiliate and webmaster tools: Amazon Associates earnings audit, commission calculators, rate tables, link tools, a URL submitter and a backlink directory. Everything runs in your browser.', 'Ferramentas gratuitas de afiliação e para webmasters: auditoria de ganhos Amazon Associates, calculadoras de comissões, tabelas de taxas, ferramentas de links, um enviador de URLs e um diretório de backlinks. Tudo roda no navegador.'],
    ['A growing set of free affiliate and webmaster tools that run entirely in your browser: earnings audit, commission calculators, link tools, a URL submitter and a backlink directory.', 'Um conjunto crescente de ferramentas gratuitas de afiliação e para webmasters que rodam inteiramente no seu navegador: auditoria de ganhos, calculadoras de comissões, ferramentas de links, um enviador de URLs e um diretório de backlinks.'],
    ['100% free', '100% grátis'],
    ['Affiliate & webmaster tools that run in your browser — no sign-up, no install.', 'Ferramentas de afiliação e para webmasters que rodam no seu navegador — sem cadastro, sem instalação.'],
    ['Free tools that help you earn more from every link, click &amp; report', 'Ferramentas gratuitas que ajudam você a ganhar mais com cada link, clique e relatório'],
    ['Not a single-purpose tool. A complete earning toolkit.', 'Não é uma ferramenta de um só propósito. Um kit completo de ganhos.'],
    ['AmzLoss gives Amazon associates and independent webmasters a free, private toolkit to audit earnings, sanity-check commissions, submit URLs and build backlinks — without handing your data to anyone.', 'AmzLoss oferece aos afiliados da Amazon e webmasters independentes um kit gratuito e privado para auditar ganhos, conferir comissões, enviar URLs e construir backlinks — sem entregar seus dados a ninguém.'],
    ['Explore all tools', 'Explorar todas as ferramentas'],
    ['Audit my Amazon report', 'Auditar meu relatório da Amazon'],
    ['No account. No sign-up. Your data never leaves your device.', 'Sem conta. Sem cadastro. Seus dados nunca saem do seu dispositivo.'],
    ['8+ free tools, one toolkit', '8+ ferramentas grátis, um kit'],
    ['30+ platforms to submit URLs', '30+ plataformas para enviar URLs'],
    ['100% processed in-browser only', '100% processado apenas no navegador'],
    ['The problem', 'O problema'],
    ['Amazon quietly made affiliate earnings harder to trust', 'A Amazon tornou os ganhos de afiliados mais difíceis de confiar'],
    ['Three things quietly work against Amazon associates:', 'Três coisas agem silenciosamente contra afiliados da Amazon:'],
    ['Rates cut up to 50%', 'Taxas reduzidas em até 50%'],
    ['Categories like furniture and tools dropped from 8% to 3% — a 62% pay cut with no warning.', 'Categorias como móveis e ferramentas caíram de 8% para 3% — um corte de 62% sem aviso.'],
    ['Reporting got weaker', 'Os relatórios enfraqueceram'],
    ['The dashboard hides the math. You see a number, not how it was calculated.', 'O painel esconde a matemática. Você vê um número, não como foi calculado.'],
    ['Nobody checks the math', 'Ninguém confere a matemática'],
    ['If a commission is miscalculated or a click stolen, you will not catch it by glancing at the summary.', 'Se uma comissão for calculada errado ou um clique roubado, você não perceberá olhando o resumo.'],
    ['That is where AmzLoss helps — free tools that show the math, check the rates and help you get found.', 'É aí que AmzLoss ajuda — ferramentas gratuitas que mostram a matemática, conferem as taxas e ajudam você a ser encontrado.'],
    ['How it works', 'Como funciona'],
    ['Three steps, no account required', 'Três passos, sem conta necessária'],
    ['Pick a tool', 'Escolha uma ferramenta'],
    ['Open any tool on this site. Everything runs locally in your browser.', 'Abra qualquer ferramenta neste site. Tudo roda localmente no seu navegador.'],
    ['Use it privately', 'Use com privacidade'],
    ['Paste your numbers, rates or URLs. Nothing is uploaded or stored.', 'Cole seus números, taxas ou URLs. Nada é enviado ou armazenado.'],
    ['Act on the result', 'Aja conforme o resultado'],
    ['Audit a report, submit a URL, or list your site in the backlink directory.', 'Audite um relatório, envie uma URL ou liste seu site no diretório de backlinks.'],
    ['Tools', 'Ferramentas'],
    ['Free tools for Amazon associates &amp; webmasters', 'Ferramentas gratuitas para afiliados da Amazon e webmasters'],
    ['Commission Calculator', 'Calculadora de comissões'],
    ['Estimate earnings from clicks, price and category rate — instantly.', 'Estime ganhos a partir de cliques, preço e taxa da categoria — instantaneamente.'],
    ['Rate Table', 'Tabela de taxas'],
    ['Current Amazon Associates commission rates by category, with recent cuts.', 'Taxas de comissão atuais da Amazon Associates por categoria, com cortes recentes.'],
    ['Earnings Audit', 'Auditoria de ganhos'],
    ['Upload a report and check the math yourself — your data stays on your device.', 'Envie um relatório e confira a matemática você mesmo — seus dados ficam no seu dispositivo.'],
    ['Break-even Calculator', 'Calculadora de ponto de equilíbrio'],
    ['How many sales you need before a campaign pays for itself.', 'Quantas vendas você precisa para uma campanha se pagar.'],
    ['Network Calculator', 'Calculadora de redes'],
    ['Compare earnings across affiliate programs, not just Amazon.', 'Compare ganhos entre programas de afiliação, não só a Amazon.'],
    ['Link Builder', 'Criador de links'],
    ['Turn any product URL into a clean, tagged affiliate link.', 'Transforme qualquer URL de produto em um link de afiliado limpo e etiquetado.'],
    ['URL Submitter', 'Enviador de URLs'],
    ['Ping 30+ platforms (Google, Bing, IndexNow) so new pages get indexed faster.', 'Faça ping em mais de 30 plataformas (Google, Bing, IndexNow) para indexar páginas mais rápido.'],
    ['Backlink Directory', 'Diretório de backlinks'],
    ['List your site and discover others to grow referral traffic.', 'Liste seu site e descubra outros para crescer seu tráfego de referência.'],
    ['A simple strategy', 'Uma estratégia simples'],
    ['One quiet habit that compounds', 'Um hábito silencioso que se acumula'],
    ['Most associates optimize a page once and move on. The ones who grow treat indexing and backlinks as a weekly habit.', 'A maioria otimiza uma página uma vez e segue em frente. Quem cresce trata indexação e backlinks como um hábito semanal.'],
    ['Every Monday, pick one URL and submit it everywhere, then list one backlink. Small, consistent actions beat occasional sprints.', 'Toda segunda, escolha uma URL e envie para todos os lugares, depois liste um backlink. Ações pequenas e constantes vencem sprints ocasionais.'],
    ['Free vs paid', 'Grátis vs pago'],
    ['Everything free, no catch', 'Tudo grátis, sem letras miúdas'],
    ['Every tool on this site', 'Cada ferramenta deste site'],
    ['No account needed', 'Sem conta necessária'],
    ['Private by design', 'Privado por design'],
    ['Paid (never required)', 'Pago (nunca necessário)'],
    ['Sponsor the project', 'Patrocine o projeto'],
    ['Remove ads', 'Remover anúncios'],
    ['Priority feature requests', 'Pedidos de recursos prioritários'],
    ['Who it is for', 'Para quem é'],
    ['Built for people who publish and promote', 'Feito para quem publica e promove'],
    ['Amazon Associates', 'Amazon Associates'],
    ['Check if rate cuts or miscalculations are costing you.', 'Verifique se cortes de taxas ou cálculos errados estão custando caro.'],
    ['Webmasters', 'Webmasters'],
    ['Get pages indexed faster and grow referral traffic.', 'Indexe páginas mais rápido e cresça seu tráfego de referência.'],
    ['Content creators', 'Criadores de conteúdo'],
    ['Turn product URLs into clean affiliate links in seconds.', 'Transforme URLs de produtos em links de afiliado limpos em segundos.'],
    ['Agencies', 'Agências'],
    ['Give clients a private, branded earnings check.', 'Ofereça aos clientes uma verificação de ganhos privada e com sua marca.'],
    ['What people say', 'O que dizem'],
    ['Real feedback from affiliate publishers', 'Feedback real de publicadores afiliados'],
    ['Trusted by publishers', 'Confiado por publicadores'],
    ['Stay in the loop', 'Fique por dentro'],
    ['New tools, rate-change alerts and indexing tips — no spam.', 'Novas ferramentas, alertas de mudança de taxas e dicas de indexação — sem spam.'],
    ['Get update', 'Receber novidades'],
    ['We respect your inbox. Unsubscribe anytime.', 'Respeitamos sua caixa de entrada. Cancele quando quiser.'],
    ['Frequently asked questions', 'Perguntas frequentes'],
    ['Common questions about AmzLoss', 'Perguntas comuns sobre AmzLoss'],
    ['Are my details safe with AmzLoss?', 'Meus dados estão seguros com AmzLoss?'],
    ['Yes. Everything is processed in your browser. We never upload, store or see your earnings, links or URLs.', 'Sim. Tudo é processado no seu navegador. Nunca enviamos, armazenamos ou vemos seus ganhos, links ou URLs.'],
    ['Are these tools only for Amazon affiliates?', 'Essas ferramentas são só para afiliados da Amazon?'],
    ['No. The audit, rate table, calculator and break-even tool focus on Amazon because that is where underpayment is hardest to verify, but the network calculator, link tools, URL submitter and backlink directory work for any webmaster.', 'Não. A auditoria, tabela de taxas, calculadora e ferramenta de ponto de equilíbrio focam na Amazon porque é onde pagamentos errados são mais difíceis de verificar, mas a calculadora de redes, ferramentas de links, enviador de URLs e diretório de backlinks funcionam para qualquer webmaster.'],
    ['Do I need to create an account?', 'Preciso criar uma conta?'],
    ['No. Every tool works without sign-up. Your data never leaves your device.', 'Não. Cada ferramenta funciona sem cadastro. Seus dados nunca saem do seu dispositivo.'],
    ['Is AmzLoss really free?', 'AmzLoss é realmente grátis?'],
    ['Yes. All tools are free. Paid options (sponsorship, ad removal) are never required.', 'Sim. Todas as ferramentas são grátis. Opções pagas (patrocínio, remoção de anúncios) nunca são necessárias.'],
    ['How do I report a bug or request a tool?', 'Como reporto um bug ou peço uma ferramenta?'],
    ['Email admin@amzloss.com with the details. Feature requests from sponsors get priority.', 'Envie um e-mail para admin@amzloss.com com os detalhes. Pedidos de recursos de patrocinadores têm prioridade.'],
    ['Ready to take control of your affiliate earnings?', 'Pronto para assumir o controle dos seus ganhos de afiliado?'],
    ['Start with a free earnings audit — no account, no risk.', 'Comece com uma auditoria de ganhos grátis — sem conta, sem risco.'],
    ['More tools', 'Mais ferramentas'],
    ['Guides', 'Guias'],
    ['Company', 'Empresa'],
    ['Discover more', 'Descobrir mais'],
    ['AmzLoss', 'AmzLoss'],
    ['All rights reserved.', 'Todos os direitos reservados.'],
    ['Privacy-first tools that help you earn, verify and grow.', 'Ferramentas priorizando privacidade que ajudam você a ganhar, verificar e crescer.'],
    ['Affiliate tools', 'Ferramentas de afiliação'],
    ['Webmaster tools', 'Ferramentas para webmasters'],
    ['About', 'Sobre'],
    ['Pricing', 'Preços'],
    ['FAQ', 'FAQ'],
    ['Contact', 'Contato'],
    ['Blog', 'Blog'],
    ['Terms', 'Termos'],
    ['Privacy', 'Privacidade'],
    ['Sitemap', 'Mapa do site'],
    ['Follow us', 'Siga-nos'],
  ],
  fr: [
    ['Free Amazon Affiliate Tools | Earnings Audit | AmzLoss', "Outils gratuits pour affiliés Amazon | Audit de gains | AmzLoss"],
    ['Free Amazon affiliate tools: audit your earnings, calculate commissions, check 2026 rates, build links and grow backlinks — all in your browser, no sign-up.', "Outils gratuits pour affiliés Amazon : auditez vos gains, calculez les commissions, consultez les tarifs 2026, créez des liens et développez vos backlinks — tout dans votre navigateur, sans inscription."],
    ['amazon affiliate tools, amazon associates earnings audit, amazon commission calculator, amazon associates commission rate table, amazon affiliate rate cuts 2026, amazon affiliate underpayment, free affiliate tools, url submitter, indexnow, backlink directory, link builder, webmaster tools', "outils affiliés amazon, audit de gains amazon associates, calculateur de commissions amazon, tableau des tarifs amazon associates, baisses de tarifs amazon 2026, paiement incorrect amazon, outils d'affiliation gratuits, soumetteur d'urls, indexnow, annuaire de backlinks, générateur de liens, outils pour webmasters"],
    ['Free affiliate and webmaster tools: Amazon Associates earnings audit, commission calculators, rate tables, link tools, a URL submitter and a backlink directory. Everything runs in your browser.', "Outils d'affiliation et pour webmasters gratuits : audit de gains Amazon Associates, calculateurs de commissions, tableaux des tarifs, outils de liens, un soumetteur d'URLs et un annuaire de backlinks. Tout fonctionne dans votre navigateur."],
    ['A growing set of free affiliate and webmaster tools that run entirely in your browser: earnings audit, commission calculators, link tools, a URL submitter and a backlink directory.', "Un ensemble croissant d'outils d'affiliation et pour webmasters gratuits qui fonctionnent entièrement dans votre navigateur : audit de gains, calculateurs de commissions, outils de liens, un soumetteur d'URLs et un annuaire de backlinks."],
    ['100% free', "100% gratuit"],
    ['Affiliate & webmaster tools that run in your browser — no sign-up, no install.', "Outils d'affiliation et pour webmasters qui fonctionnent dans votre navigateur — sans inscription, sans installation."],
    ['Free tools that help you earn more from every link, click &amp; report', "Des outils gratuits qui vous aident à gagner plus sur chaque lien, clic et rapport"],
    ['Not a single-purpose tool. A complete earning toolkit.', "Pas un outil à usage unique. Une boîte à outils de gains complète."],
    ['AmzLoss gives Amazon associates and independent webmasters a free, private toolkit to audit earnings, sanity-check commissions, submit URLs and build backlinks — without handing your data to anyone.', "AmzLoss offre aux affiliés Amazon et aux webmasters indépendants une boîte à outils gratuite et privée pour auditer les gains, vérifier les commissions, soumettre des URLs et créer des backlinks — sans confier vos données à quiconque."],
    ['Explore all tools', "Explorer tous les outils"],
    ['Audit my Amazon report', "Auditer mon rapport Amazon"],
    ['No account. No sign-up. Your data never leaves your device.', "Pas de compte. Pas d'inscription. Vos données ne quittent jamais votre appareil."],
    ['8+ free tools, one toolkit', "8+ outils gratuits, une boîte à outils"],
    ['30+ platforms to submit URLs', "30+ plateformes pour soumettre des URLs"],
    ['100% processed in-browser only', "100% traité uniquement dans le navigateur"],
    ['The problem', "Le problème"],
    ['Amazon quietly made affiliate earnings harder to trust', "Amazon a rendu les gains d'affiliés plus difficiles à vérifier"],
    ['Three things quietly work against Amazon associates:', "Trois choses agissent silencieusement contre les affiliés Amazon :"],
    ['Rates cut up to 50%', "Tarifs réduits jusqu'à 50 %"],
    ['Categories like furniture and tools dropped from 8% to 3% — a 62% pay cut with no warning.', "Des catégories comme meubles et outils sont passées de 8 % à 3 % — une baisse de 62 % sans avertissement."],
    ['Reporting got weaker', "Les rapports ont faibli"],
    ['The dashboard hides the math. You see a number, not how it was calculated.', "Le tableau de bord cache les calculs. Vous voyez un chiffre, pas comment il a été calculé."],
    ['Nobody checks the math', "Personne ne vérifie les calculs"],
    ['If a commission is miscalculated or a click stolen, you will not catch it by glancing at the summary.', "Si une commission est mal calculée ou un clic volé, vous ne le verrez pas en jetant un œil au résumé."],
    ['That is where AmzLoss helps — free tools that show the math, check the rates and help you get found.', "C'est là qu'AmzLoss aide — des outils gratuits qui montrent les calculs, vérifient les tarifs et vous aident à être trouvé."],
    ['How it works', "Comment ça marche"],
    ['Three steps, no account required', "Trois étapes, sans compte requis"],
    ['Pick a tool', "Choisissez un outil"],
    ['Open any tool on this site. Everything runs locally in your browser.', "Ouvrez n'importe quel outil sur ce site. Tout s'exécute localement dans votre navigateur."],
    ['Use it privately', "Utilisez-le en privé"],
    ['Paste your numbers, rates or URLs. Nothing is uploaded or stored.', "Collez vos chiffres, tarifs ou URLs. Rien n'est téléversé ni stocké."],
    ['Act on the result', "Agissez selon le résultat"],
    ['Audit a report, submit a URL, or list your site in the backlink directory.', "Auditez un rapport, soumettez une URL ou listez votre site dans l'annuaire de backlinks."],
    ['Tools', "Outils"],
    ['Free tools for Amazon associates &amp; webmasters', "Outils gratuits pour affiliés Amazon et webmasters"],
    ['Commission Calculator', "Calculateur de commissions"],
    ['Estimate earnings from clicks, price and category rate — instantly.', "Estimez les gains à partir des clics, du prix et du taux de catégorie — instantanément."],
    ['Rate Table', "Tableau des tarifs"],
    ['Current Amazon Associates commission rates by category, with recent cuts.', "Taux de commission Amazon Associates actuels par catégorie, avec les baisses récentes."],
    ['Earnings Audit', "Audit de gains"],
    ['Upload a report and check the math yourself — your data stays on your device.', "Téléversez un rapport et vérifiez les calculs vous-même — vos données restent sur votre appareil."],
    ['Break-even Calculator', "Calculateur de seuil de rentabilité"],
    ['How many sales you need before a campaign pays for itself.', "Combien de ventes il vous faut avant qu'une campagne ne soit rentable."],
    ['Network Calculator', "Calculateur de réseau"],
    ['Compare earnings across affiliate programs, not just Amazon.', "Comparez les gains entre programmes d'affiliation, pas seulement Amazon."],
    ['Link Builder', "Générateur de liens"],
    ['Turn any product URL into a clean, tagged affiliate link.', "Transformez toute URL produit en un lien d'affiliation propre et balisé."],
    ['URL Submitter', "Soumetteur d'URLs"],
    ['Ping 30+ platforms (Google, Bing, IndexNow) so new pages get indexed faster.', "Pingez plus de 30 plateformes (Google, Bing, IndexNow) pour indexer les pages plus vite."],
    ['Backlink Directory', "Annuaire de backlinks"],
    ['List your site and discover others to grow referral traffic.', "Listez votre site et découvrez d'autres sites pour développer votre trafic de référence."],
    ['A simple strategy', "Une stratégie simple"],
    ['One quiet habit that compounds', "Une habitude discrète qui se cumule"],
    ['Most associates optimize a page once and move on. The ones who grow treat indexing and backlinks as a weekly habit.', "La plupart des affiliés optimisent une page une fois puis passent à autre chose. Ceux qui grandissent traitent l'indexation et les backlinks comme une habitude hebdomadaire."],
    ['Every Monday, pick one URL and submit it everywhere, then list one backlink. Small, consistent actions beat occasional sprints.', "Chaque lundi, choisissez une URL et soumettez-la partout, puis listez un backlink. De petites actions constantes battent les sprints occasionnels."],
    ['Free vs paid', "Gratuit vs payant"],
    ['Everything free, no catch', "Tout gratuit, sans piège"],
    ['Every tool on this site', "Chaque outil de ce site"],
    ['No account needed', "Aucun compte requis"],
    ['Private by design', "Privé par conception"],
    ['Paid (never required)', "Payant (jamais requis)"],
    ['Sponsor the project', "Sponsoriser le projet"],
    ['Remove ads', "Supprimer les publicités"],
    ['Priority feature requests', "Demandes de fonctionnalités prioritaires"],
    ['Who it is for', "À qui cela s'adresse"],
    ['Built for people who publish and promote', "Conçu pour ceux qui publient et promeuvent"],
    ['Amazon Associates', "Amazon Associates"],
    ['Check if rate cuts or miscalculations are costing you.', "Vérifiez si les baisses de tarifs ou les erreurs de calcul vous coûtent cher."],
    ['Webmasters', "Webmasters"],
    ['Get pages indexed faster and grow referral traffic.', "Faites indexer les pages plus vite et développez votre trafic de référence."],
    ['Content creators', "Créateurs de contenu"],
    ['Turn product URLs into clean affiliate links in seconds.', "Transformez des URLs produit en liens d'affiliation propres en quelques secondes."],
    ['Agencies', "Agences"],
    ['Give clients a private, branded earnings check.', "Offrez à vos clients une vérification de gains privée et à votre marque."],
    ['What people say', "Ce que disent les gens"],
    ['Real feedback from affiliate publishers', "Vrais retours d'affiliés éditeurs"],
    ['Trusted by publishers', "Apprécié des éditeurs"],
    ['Stay in the loop', "Restez informé"],
    ['New tools, rate-change alerts and indexing tips — no spam.', "Nouveaux outils, alertes de changement de tarifs et astuces d'indexation — sans spam."],
    ['Get update', "Recevoir les nouveautés"],
    ['We respect your inbox. Unsubscribe anytime.', "Nous respectons votre boîte mail. Désabonnement à tout moment."],
    ['Frequently asked questions', "Questions fréquentes"],
    ['Common questions about AmzLoss', "Questions courantes sur AmzLoss"],
    ['Are my details safe with AmzLoss?', "Mes données sont-elles en sécurité avec AmzLoss ?"],
    ['Yes. Everything is processed in your browser. We never upload, store or see your earnings, links or URLs.', "Oui. Tout est traité dans votre navigateur. Nous ne téléversons, ne stockons ni ne voyons vos gains, liens ou URLs."],
    ['Are these tools only for Amazon affiliates?', "Ces outils sont-ils réservés aux affiliés Amazon ?"],
    ['No. The audit, rate table, calculator and break-even tool focus on Amazon because that is where underpayment is hardest to verify, but the network calculator, link tools, URL submitter and backlink directory work for any webmaster.', "Non. L'audit, le tableau des tarifs, le calculateur et l'outil de seuil de rentabilité se concentrent sur Amazon car c'est là que les paiements erronés sont les plus difficiles à vérifier, mais le calculateur de réseau, les outils de liens, le soumetteur d'URLs et l'annuaire de backlinks fonctionnent pour tout webmaster."],
    ['Do I need to create an account?', "Dois-je créer un compte ?"],
    ['No. Every tool works without sign-up. Your data never leaves your device.', "Non. Chaque outil fonctionne sans inscription. Vos données ne quittent jamais votre appareil."],
    ['Is AmzLoss really free?', "AmzLoss est-il vraiment gratuit ?"],
    ['Yes. All tools are free. Paid options (sponsorship, ad removal) are never required.', "Oui. Tous les outils sont gratuits. Les options payantes (parrainage, suppression des publicités) ne sont jamais requises."],
    ['How do I report a bug or request a tool?', "Comment signaler un bug ou demander un outil ?"],
    ['Email admin@amzloss.com with the details. Feature requests from sponsors get priority.', "Écrivez à admin@amzloss.com avec les détails. Les demandes de parrainés sont prioritaires."],
    ['Ready to take control of your affiliate earnings?', "Prêt à prendre le contrôle de vos gains d'affilié ?"],
    ['Start with a free earnings audit — no account, no risk.', "Commencez par un audit de gains gratuit — sans compte, sans risque."],
    ['More tools', "Plus d'outils"],
    ['Guides', "Guides"],
    ['Company', "Société"],
    ['Discover more', "Découvrir plus"],
    ['AmzLoss', "AmzLoss"],
    ['All rights reserved.', "Tous droits réservés."],
    ['Privacy-first tools that help you earn, verify and grow.', "Des outils centrés sur la confidentialité qui vous aident à gagner, vérifier et grandir."],
    ['Affiliate tools', "Outils d'affiliation"],
    ['Webmaster tools', "Outils pour webmasters"],
    ['About', "À propos"],
    ['Pricing', "Tarifs"],
    ['FAQ', "FAQ"],
    ['Contact', "Contact"],
    ['Blog', "Blog"],
    ['Terms', "Conditions"],
    ['Privacy', "Confidentialité"],
    ['Sitemap', "Plan du site"],
    ['Follow us', "Suivez-nous"],
  ],
};

function build(lang, pairs) {
  let html = src;

  for (const [en, tr] of pairs) {
    if (!en) continue;
    html = html.split(en).join(tr);
  }

  // language attribute
  html = html.replace('<html lang="en">', `<html lang="${lang}">`);

  // canonical -> localized + hreflang block
  const canonical = '<link rel="canonical" href="https://amzloss.com/">';
  const hreflang = [
    '<link rel="canonical" href="https://amzloss.com/' + lang + '/">',
    '<link rel="alternate" hreflang="en" href="https://amzloss.com/">',
    '<link rel="alternate" hreflang="es" href="https://amzloss.com/es/">',
    '<link rel="alternate" hreflang="de" href="https://amzloss.com/de/">',
    '<link rel="alternate" hreflang="pt" href="https://amzloss.com/pt/">',
    '<link rel="alternate" hreflang="fr" href="https://amzloss.com/fr/">',
    '<link rel="alternate" hreflang="x-default" href="https://amzloss.com/">',
  ].join('\n  ');
  html = html.replace(canonical, hreflang);

  // og:url + og:locale
  html = html.split('<meta property="og:url" content="https://amzloss.com/">')
    .join('<meta property="og:url" content="https://amzloss.com/' + lang + '/">');
  const localeMap = { es: 'es_ES', de: 'de_DE', pt: 'pt_BR', fr: 'fr_FR' };
  html = html.split('<meta property="og:locale" content="en_US">')
    .join('<meta property="og:locale" content="' + (localeMap[lang] || 'en_US') + '">');

  // relative asset paths (style, js, sw) need to step up one directory
  html = html.split('href="assets/css/style.css"').join('href="../assets/css/style.css"');
  html = html.split('src="js/nav.js"').join('src="../js/nav.js"');
  html = html.split('src="js/i18n.js"').join('src="../js/i18n.js"');
  html = html.split('navigator.serviceWorker.register("sw.js")').join('navigator.serviceWorker.register("../sw.js")');

  // relative in-page links to other html pages -> step up so they resolve to root
  html = html.replace(/href="([a-z0-9-]+\.html)"/g, 'href="../$1"');

  // mark this page as a translated peer in the manifest-aware bar
  fs.mkdirSync(path.join(ROOT, lang), { recursive: true });
  fs.writeFileSync(path.join(ROOT, lang, 'index.html'), html);
  console.log('wrote', lang + '/index.html', '(' + html.length + ' bytes)');
}

for (const [lang, pairs] of Object.entries(MAPS)) {
  build(lang, pairs);
}
